apiVersion: v1
kind: Service
metadata:
  name: influxdb-svc
  annotations:
    metallb.universe.tf/allow-shared-ip: default
spec:
  ports:
    - port: 8086
      protocol: TCP
      targetPort: 8086
  selector:
    app: influxdb
  sessionAffinity: None
  type: ClusterIP