apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deploy
spec:
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app:
          mysql
    spec:
      containers:
      - name: mysql
        image: mysql_image
        imagePullPolicy: Never
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
          - name: mysql-pv-volume
            mountPath: /var/lib/mysql
      volumes:
      - name: mysql-pv-volume
        persistentVolumeClaim:
          claimName: mysql-pv-claim