apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
  annotations:
    metallb.universe.tf/allow-shared-ip: default
spec:
  selector:
    app: nginx
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
    - name: https
      protocol: TCP
      port: 443
      targetPort: 443
  type: LoadBalancer
  loadBalancerIP: 192.168.99.100