apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin-deploy
spec:
  selector:
    matchLabels:
      app: phpmyadmin
  template:
    metadata:
      labels:
        app:
          phpmyadmin
    spec:
      containers:
      - name: phpmyadmin
        image: phpmyadmin_image
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
          name: php