apiVersion: v1
kind: Service
metadata:
  name: wordpress-svc
  annotations:
    metallb.universe.tf/allow-shared-ip: default
spec:
  selector:
    app: wordpress
  ports:
    - name: wordpress
      protocol: TCP
      port: 5050
      targetPort: 5050
  type: LoadBalancer
  loadBalancerIP: 192.168.99.100