apiVersion: v1
kind: Service
metadata:
  name: ftps-svc
  annotations:
    metallb.universe.tf/allow-shared-ip: default
spec:
  ports:
    - port: 21
      protocol: TCP
      targetPort: 21
      name: ftps
    - protocol: TCP
      port: 20
      targetPort: 20
      name: ftp
    - protocol: TCP
      port: 10000
      targetPort: 10000
      name: pasv
  selector:
    app: ftps
  sessionAffinity: None
  type: LoadBalancer
  loadBalancerIP: 192.168.99.100